// Source-detector parity runner.
//
// Reads fixture JSON files generated by backend/scripts/dump_detector_fixture.py
// and checks that detectSources() (the TS port) produces the same sources
// and `numbered` flag as detect_sources (the Python original).
//
// Run:
//     npx tsx scripts/detector-parity.ts
//
// Fixtures are loaded from <repo-root>/test-fixtures/detector/*.json. If the
// directory does not exist, the runner exits with a clear message so the
// user knows to run the dump script first.

import { readdirSync, readFileSync, existsSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import type { SourceRectangle } from '../src/renderer/src/lib/api/types'
import { detectSources } from '../src/renderer/src/lib/pdf/source-detector'
import type { ParsedPdf } from '../src/renderer/src/lib/pdf/types'

interface Fixture {
  pdf: ParsedPdf
  expected: {
    numbered: boolean
    sources: SourceRectangle[]
  }
}

const HERE = dirname(fileURLToPath(import.meta.url))
const REPO_ROOT = resolve(HERE, '..')
const FIXTURE_DIR = join(REPO_ROOT, 'test-fixtures', 'detector')

interface Failure {
  reason: string
}

function compareSource(expected: SourceRectangle, got: SourceRectangle): string | null {
  if (expected.ref_number !== got.ref_number) {
    return `ref_number differs: expected=${expected.ref_number} got=${got.ref_number}`
  }
  if (expected.text.trim() !== got.text.trim()) {
    return `text differs`
  }
  const eb = expected.bbox
  const gb = got.bbox
  if (
    eb.page !== gb.page ||
    Math.abs(eb.x0 - gb.x0) > 0.5 ||
    Math.abs(eb.y0 - gb.y0) > 0.5 ||
    Math.abs(eb.x1 - gb.x1) > 0.5 ||
    Math.abs(eb.y1 - gb.y1) > 0.5
  ) {
    return `bbox differs: expected=${JSON.stringify(eb)} got=${JSON.stringify(gb)}`
  }
  return null
}

function runFixture(fixture: Fixture): Failure[] {
  const result = detectSources(fixture.pdf)
  const failures: Failure[] = []

  if (result.numbered !== fixture.expected.numbered) {
    failures.push({
      reason: `numbered flag differs: expected=${fixture.expected.numbered} got=${result.numbered}`,
    })
  }

  if (result.sources.length !== fixture.expected.sources.length) {
    failures.push({
      reason: `source count differs: expected=${fixture.expected.sources.length} got=${result.sources.length}`,
    })
  }

  const n = Math.min(result.sources.length, fixture.expected.sources.length)
  for (let i = 0; i < n; i++) {
    const diff = compareSource(fixture.expected.sources[i], result.sources[i])
    if (diff) failures.push({ reason: `source[${i}]: ${diff}` })
  }

  return failures
}

function main(): number {
  if (!existsSync(FIXTURE_DIR)) {
    console.error(`[parity] fixture directory not found: ${FIXTURE_DIR}`)
    console.error('[parity] run `python backend/scripts/dump_detector_fixture.py <pdf>` first')
    return 2
  }

  const fixtureFiles = readdirSync(FIXTURE_DIR).filter(f => f.endsWith('.json'))
  if (fixtureFiles.length === 0) {
    console.error(`[parity] no fixtures in ${FIXTURE_DIR}`)
    return 2
  }

  let totalFailures = 0
  for (const file of fixtureFiles) {
    const path = join(FIXTURE_DIR, file)
    const fixture = JSON.parse(readFileSync(path, 'utf8')) as Fixture
    const failures = runFixture(fixture)
    if (failures.length === 0) {
      const n = fixture.expected.sources.length
      console.log(`[pass] ${file} (${n} sources, numbered=${fixture.expected.numbered})`)
    } else {
      totalFailures += failures.length
      console.log(`[fail] ${file} (${failures.length} issues)`)
      for (const f of failures) console.log(`       ${f.reason}`)
    }
  }

  if (totalFailures > 0) {
    console.error(`\n[parity] ${totalFailures} failures across ${fixtureFiles.length} fixtures`)
    return 1
  }

  console.log(`\n[parity] all ${fixtureFiles.length} fixtures pass`)
  return 0
}

process.exit(main())
